// <auto-generated />
using System;
using InsuranceSystem.Infrastructure.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsuranceSystem.API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InsuranceSystem.Domain.Policy.PolicyHolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalIDNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PolicyHolders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2023, 11, 15, 11, 47, 34, 220, DateTimeKind.Local).AddTicks(1690),
                            DateModified = new DateTime(2023, 11, 15, 11, 47, 34, 220, DateTimeKind.Local).AddTicks(1720),
                            DateOfBirth = new DateTime(2000, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Precious",
                            NationalIDNumber = "NGN0014AA",
                            PolicyNumber = "H2441",
                            Surname = "Chukwuma"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2023, 11, 15, 11, 47, 34, 220, DateTimeKind.Local).AddTicks(1730),
                            DateModified = new DateTime(2023, 11, 15, 11, 47, 34, 220, DateTimeKind.Local).AddTicks(1730),
                            DateOfBirth = new DateTime(2001, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gladys",
                            NationalIDNumber = "NGN0024AA",
                            PolicyNumber = "H2442",
                            Surname = "Chukwuma"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
